---
cds:
  datasource:
    auto-config.enabled: false
  remote.services:
    - name: "TodoEntryV2"
      destination:
        name: "SFSF-BASIC-ADMIN"
        type: "odata-v2"
        suffix: "/odata/v2"
        service: "TodoEntryV2"
    - name: "Goal_101"
      destination:
        name: "SFSF-BASIC-ADMIN"
        type: "odata-v2"
        suffix: "/odata/v2"
        service: "Goal_101"
# ---
# spring:
#   config.activate.on-profile: local
logging:
  level:
    # org.springframework: DEBUG
    # org.springframework.security: DEBUG
    com.sap.cloud.sdk: DEBUG
    com.sap.cds: DEBUG
    # org.apache.http.wire: DEBUG